### ISSUE TITLE
Donate

### ISSUE THREAD

**Issue by PLG** [chriszarate/supergenpass#25]
Chris, 

I've been using SGP for years and so does  a few other ppl I recommended it to. Perhaps you could add a donate button to get some kickback support.

**Comment by PLG** [comment]
Chris... consider this ... http://www.patreon.com/

**Comment by PLG** [comment]
Chris, you really should consider putting a donate button on your website (unless you are filthy rich). I signed up for gittip today, but I really would recommend: http://www.patreon.com/
Same thing, just more popular and flashy.

**Comment by scottchiefbaker** [comment]
I use flattr through github. I'd be happy to contribute that way.

**Comment by PLG** [comment]
I tried flattr. Not my cup of tea. Didn't like the way it split your monthly budget. Would much rather have a set rate.
