### ISSUE TITLE
support for symbols, bcrypt

### ISSUE THREAD

**Issue by cmcnulty** [chriszarate/supergenpass#4]
I've forked SuperGenPass to include support for bcrypt and symbols using base85 rather than base64.  For me this addresses the two biggest weaknesses of SGP:

1) SGP generated password is unnecessarily weak, and can be more easily compromised when password database is compromised (see In, Linked).  This can be resolved by manually padding the SGP password but, I'd prefer if the tool did the work.

2) Master password retrieval is potentially too easy because of the inherent weakness of using a "fast" hashing algorithm if the domain/SGP password has already been compromised (see 1).  By using bcrypt to arrive at the SGP password, it becomes infeasible to brute-force even a relatively weak master password.

See: cmcnulty/SuperGenPass@5875e2d0eb4349b13621d32b75a789c1443506ab

**Comment by weakish** [comment]
> 1) SGP generated password is unnecessarily weak, and can be more easily compromised when password database is compromised

@cmcnulty I thought knowing `md5(pw:A)` and `A` does not helps cracking `pw` or `md5(pw:B)` where `B` is known, unless `pw` is weak.

If `pw` is weak,  `pkdf2`, `bcrypt` and `scrypt`  do require more time to crack.
