### ISSUE TITLE
allow password libraries to be async

### ISSUE THREAD

**Issue by cmcnulty** [chriszarate/supergenpass#47]
In order to support alternate password generation libraries, it would be nice if the SGP (and the API of supergenpass-lib) provided a mechanism for both asynchronous password generation.  This would take the form of two callbacks passed into the options array of the password generator function, a progress callback and a completed callback.  I already have the code in my fork, I'll split it off into a pull request whenever I get a chance, if I get an indication that such a pull would be considered.

**Comment by chriszarate** [comment]
Closing as this has been addressed in supergenpass-lib.
