### ISSUE TITLE
"SGP may be blocked on this site by a security setting..." missing in Firefox

### ISSUE THREAD

**Issue by scottchiefbaker** [chriszarate/supergenpass#56]
Github blocks SGP (which we already know). In Chrome you get the following warning:

> SGP may be blocked on this site by a security setting. You may wish to open the mobile version.

but in Firefox no warning or window pops up.

**Comment by chriszarate** [comment]
I can't find a good solution to this. Firefox just won't let me detect when the script has been blocked (there's no error to trap). This is probably a good security move, but a bummer for SGP.

**Comment by weepy** [comment]
why does github block SGP ?

**Comment by StevenQuick** [comment]
CSP (Content Security Policy) is becoming more widespread
https://en.wikipedia.org/wiki/Content_Security_Policy
http://www.html5rocks.com/en/tutorials/security/content-security-policy/

SGP will probably have to go back to javascriptlet or become a browser addon for it to remain useless on most major sites.

**Comment by StevenQuick** [comment]
Hmm this one is pretty cool just a chrome extension wrapping your mobile page
https://github.com/benol/MySuperGenPass

**Comment by scottchiefbaker** [comment]
This is no longer an issue. Firefox must have fixed it?

**Comment by StevenQuick** [comment]
It's still an issue in Firefox 41.0.2 for me, try use the SGP bookmarklet on github blocked by CSP
