### ISSUE TITLE
Password length through parameter.

### ISSUE THREAD

**Issue by PLG** [chriszarate/supergenpass#57]
Hello Chris, 

I have a feature request or an issue, depending... One of the benefits of your old site was that you could configure SGP to be of a specific length in the booklet. Yes, you have the option to set one length, but there are sites with password length limitations. So, for those exceptions I previously created one bookmark for each exceptional length, ex: 10 and 16. If I want to generate the exception with the new SGP, I have to change the settings and change the settings back.

So, I would like to request a solution to this; perhaps a way to configure like before. If this feature exists, then I would like to request an update on the FAQ.

Thanks for listening.

**Comment by TomasMikula** [comment]
Same issue here.

**Comment by Nako** [comment]
Confirm, I need the same functionality.

**Comment by chriszarate** [comment]
The most straightforward way to change the current behavior from "always save current settings as default" to "only save current settings as default when an explicit button is pressed." Thoughts?
