### ISSUE TITLE
new user issues for mobile

### ISSUE THREAD

**Issue by mwisnev** [chriszarate/supergenpass#59]
Let me preface my comments by noting I understand little about computers, and almost nothing about the jargon used, so I apologize for my ignorance. 

I bookmarked supergenpas for the pc, tried it with one site and all seems well.  {I do note that it says the security setting don't allow the bookmarklet to open, so I need to use the mobile version, which seems fine.  But I don't know what the security issue is or how to fix if I want to}. 

So I now try to go to my Verizon tablet and try to use it .  I downloaded the mobile app, but when I open it and type the master password and domain, it gets a different password.  one point may be that I entered a secret password on the pc, and don't seem to know how to do this for the mobile app. 

So instead I open a new tab and put in supergenpass, use mobile, and cut and paste the domain, type master, and the right password password comes up.  So I cut and paste it in the other tab, and it works. But this seems to have the following problems - I have to touch the password and show it, then copy it, so it goes on the clipboard, and then pasted it the other tab.  If I copy the hidden SPG passowrd and paste it it doesn't work

I figure I must be doing many things wrong, and any help is appreciated.

**Comment by chriszarate** [comment]
Click the "gear" icon at top right to access the advanced options and enter the secret password. 

You are correct, on touch devices you need to touch the password to reveal it, then copy it.
