### ISSUE TITLE
SuperGenPass bookmarklet exceeds iCloud bookmark size limit

### ISSUE THREAD

**Issue by cbowns** [chriszarate/supergenpass#60]
My SuperGenPass bookmarklet no longer appears on my iPhone or iPad. I hit this issue with genpass back in the day, and finally looked into why: it's 4633 bytes, and iCloud has a [per-bookmark size limit of 4kB](http://support.apple.com/en-us/HT202158).

**Comment by cbowns** [comment]
Simply running the bookmarklet through http://jsbeautifier.org and http://skalman.github.io/UglifyJS-online/ shrunk it to 2997 bytes.

**Comment by cbowns** [comment]
And once shrunk, it synced over to my devices just fine.

**Comment by cbowns** [comment]
Related issue filed on bookmarkleter as https://github.com/chriszarate/bookmarkleter/issues/4

It's odd that the SuperGenPass bookmarklet on supergenpass.com is 4.6 kB, but un- and re-compressing it with bookmarkleter yields a 3.4 kB bookmarklet.

**Comment by chriszarate** [comment]
Thanks. For some reason the current bookmarklet doesn't have any of it's variable names mangled, which is the main weight savings. Should be easy to fix.

**Comment by chriszarate** [comment]
Fixed in latest bookmarklet (`20150216`). It still URL-encodes so it's ~3.4 KB.

**Comment by cbowns** [comment]
:+1: thanks!
