### ISSUE TITLE
Some websites have minimum password requirements

### ISSUE THREAD

**Issue by victropolis** [chriszarate/supergenpass#62]
Some websites have minimum password requirements (i.e. mixed case, number, special chars, etc).  Can supergenpass be improved to support these cases?

**Comment by chriszarate** [comment]
See FAQ:

https://github.com/chriszarate/supergenpass/wiki/FAQ#site-x-has-different-password-requirements

I've chosen to keep SGP simple and not try to be inclusive of ever-increasing complexity requirements. You could look at other implementations, also in the wiki, for other approaches.
