### ISSUE TITLE
New save button missing

### ISSUE THREAD

**Issue by brianclements** [chriszarate/supergenpass#63]
Using both the bookmarklet and the mobile site, I do not see the new save button that was introduced in 0.3.6, or notice any different behavior in supergenpass. I'm on firefox. Any other information I can provide that would help?

**Comment by chriszarate** [comment]
It will take a subsequent page load after the HTML5 appcache refreshes. You are using the bookmarklet from supergenpass.com with no modifications, right?

**Comment by brianclements** [comment]
Correct, straight from the site. I had to clear my cache completely to get it to load, but now it's there. Thanks!

**Comment by chriszarate** [comment]
That's weird. I tested it in Firefox, Safari, and Chrome, and it reloaded in each. I'm about to push a new version, see if you have the same issue.

**Comment by brianclements** [comment]
Yeah same thing again, needed to clear my cache in firefox to get the 0.3.7 features. BTW that gear sticky thing fixes my problem in #51, thanks for that.
