### ISSUE TITLE
feature request: special character support

### ISSUE THREAD

**Issue by brianclements** [chriszarate/supergenpass#65]
Some websites require at least 1 special character for their password. What I've done so far is just append it to whatever the output of SGP is, but I think it'd be cool to have a checkbox that could insert some of these characters when required so that I can have consistent behavior that I don't have to think about. Not sure how easy a different encoding is to implement, but something to think about.

**Comment by chriszarate** [comment]
See FAQ:

https://github.com/chriszarate/supergenpass/wiki/FAQ#site-x-has-different-password-requirements

I've chosen to keep SGP simple and not try to be inclusive of ever-increasing complexity requirements. You could look at other implementations, also in the wiki, for other approaches.

**Comment by brianclements** [comment]
fair enough.
