### ISSUE TITLE
why have md5 and sha1 option

### ISSUE THREAD

**Issue by weepy** [chriszarate/supergenpass#66]
seems a bit unceccessary to have both. ? Can't you just pick the best one ? e.g. SHA-2 ?

**Comment by weakish** [comment]
Because MD5 is faster than SHA512?

**Comment by weepy** [comment]
Surely the speed is irrelevant since there's only one operation that takes
milliseconds

**Comment by chriszarate** [comment]
SGP has been around awhile. When it first came out, MD5 was the only option. I've since added SHA-512, but MD5 is kept as default since many users (including myself) have used it for years.
