### ISSUE TITLE
Length extension attack?

### ISSUE THREAD

**Issue by lahwran** [chriszarate/supergenpass#69]
from here, it was opened on the wrong repository: https://github.com/gfxmonk/supergenpass/issues/1

The recommended solution to length extension is apparently to use HMAC. Is there an HMAC version of supergenpass? if not, could there please be?

**Comment by PacoBell** [comment]
Twik/Phashword?

**Comment by lahwran** [comment]
What crypto do those use? are they usable without sorting any authentication data, using only a remembered password?

**Comment by chriszarate** [comment]
Covered in the linked issue and in #61.
