### ISSUE TITLE
Can't see password

### ISSUE THREAD

**Issue by llchristopherson** [chriszarate/supergenpass#71]
It seems you either took away this ability or it is no longer working. There are times when I need to see the password that supergen generates. For example, I need to put the password into my smart tv and roku. I can no longer do that. Please fix this. Or if I am not looking in the right place or not doing it right, please provide instructions.

**Comment by chriszarate** [comment]
The password is masked by default but a click/touch reveals it. Is this not the case for you?

**Comment by llchristopherson** [comment]
Okay yes that works. It is not obvious. I would recommend you give a little clue to folks. Thanks for getting back to me. I really appreciate it.
