### ISSUE TITLE
website redirect

### ISSUE THREAD

**Issue by tukw** [chriszarate/supergenpass#72]
A website that I want to visit has redirected itself to a new domain. Now the generated password is different and hence I cannot login. Is there any way that I can still produce the correct password using the old domain name?

**Comment by chriszarate** [comment]
In the SGP window, edit the domain to the old domain name (e.g., example.com). After logging in you will probably want to update your password to the new SGP produces for the new domain.

**Comment by tukw** [comment]
Thank you. I was using an old version of SGP, so I didn't see how I could change the domain name. With the latest version, my problem is solved.
