### ISSUE TITLE
Android app and mobile SGP different

### ISSUE THREAD

**Issue by gchiu** [chriszarate/supergenpass#83]
I've got the android app, but it's generating different passwords from the one at https://chriszarate.github.io/supergenpass/mobile/

Are the algorithms different?

**Comment by scottchiefbaker** [comment]
I use the Android app all the time and don't have any issues. Did you change the hashing algorithm by chance?

**Comment by gchiu** [comment]
I tried md5 and sha, both are different from the mobile app.

**Comment by gchiu** [comment]
Ok, I tried this.  I went to https://chriszarate.github.io/supergenpass/mobile/
And on Android FireFox and Windows 10 Chrome, I get different results.
So, I suspect that there's something different about Windows 10.

**Comment by scottchiefbaker** [comment]
I just tested https://chriszarate.github.io/supergenpass/mobile/ in:
- Firefox Win 10
- Edge Win 10
- Chrome Win 10
- Firefox Android,
- Chrome Android 

and got the same results on every platform. I wonder if something is up with javascript on your Android device. I am not seeing the results you are.

**Comment by gchiu** [comment]
Ok, I'm now seeing different results on Chrome Version 54.0.2840.87 m (64-bit)
 and Edge both on my Windows 10 Surface Pro

https://anon_emouse-hotmail.tinytake.com/sf/MTExNDE2NV80NDEzOTQ5

where the passphrase is "1"

**Comment by chriszarate** [comment]
In the first example, you have entered a password in the "secret password" field. In the second example, that field is empty. That is why different passwords were generated.

**Comment by gchiu** [comment]
Ah, okay.  I assumed that the second field was just the same as first as often I would type in my master password incorrectly which was a pain.  And I thought this was a fix for my own typing problems!

**Comment by chriszarate** [comment]
I can understand that confusion. Here's a tip: The icon that appears in the right-hand side of the password box is unique to your master password. You should start to recognize the icon that corresponds to your correct master password. If you type it incorrectly, a different icon will appear and you'll know you need to retype it.

**Comment by gchiu** [comment]
That's cool, a visual representation of the password.  Have you thought of providing a help link?  I've used sgp for years and never noticed these features.

**Comment by PLG** [comment]
Just tried SGP on Linux version Mac. Both Chrome and Firefox generate a different icon for my master password. I have tried many times. I will get back to you if I find more details.

**Comment by ilopata1** [comment]
If you type a domain name that includes uppercase letters manually in the web version it generates different results than if you type the same domain name in all lowercase.  The mobile app, in contrast, produces the same password regardless of case.  Ideally the passwords generated should be the same on web and Android.

**Comment by CheneyLin** [comment]
try my android app
https://www.70apps.com/supergenpass/
download link:
https://www.70apps.com/supergenpass/app-release.apk
https://itunes.apple.com/cn/app/%E8%B6%85%E7%BA%A7%E5%AF%86%E7%A0%81%E6%AD%A3%E5%BC%8F%E7%89%88/id493455722?mt=8
