### ISSUE TITLE
Non-https version of site is still available

### ISSUE THREAD

**Issue by mathbunnyru** [chriszarate/supergenpass#89]
Hello. If I click a link http://chriszarate.github.io/supergenpass/mobile/, this works for me and it's not https website.
Maybe it would be better to completely turn off an ability to use non-https version of the site?

**Comment by chriszarate** [comment]
I can't replicate this. I am redirected to the HTTPS version automatically.

**Comment by mathbunnyru** [comment]
Visit https version, then delete s button and then press enter. Then you get non https version of the website.

I think to be 100 percent sure that everything is right is to remove non https version completely.

**Comment by chriszarate** [comment]
I still can't replicate this behavior (on OS X, Safari or Chrome). Can you share your browser and OS? And can you try in an incognito / private window?

**Comment by mathbunnyru** [comment]
Doesn't work in private mode. Seems to be my cache bug. Thanks, closing the issue.
