### ISSUE TITLE
Short Password & No Symbols

### ISSUE THREAD

**Issue by alana314** [chriszarate/supergenpass#93]
I was thinking about making a tool like this and then found this. Thanks for making it!
The password it generated for me was 10 digits and could be cracked in 8 months according to https://howsecureismypassword.net. 
What if there was a version two of the software that generated longer passwords? It could truncate a SHA384 at like 12 characters, would that still be secure?
I was also thinking it could have a simple, repeatable find and replace to add symbols (*@#$%) to the password, to add to typical requirements.

**Comment by basile-laderchi** [comment]
If you click the gear on the top left you can change the password length.

Right now I am using password of 14 characters and with either the MD5 and the SHA algorithms the https://howsecureismypassword.net/ site says that they would need 10 million years to crack.

**Comment by alana314** [comment]
Got it, thanks!
