### ISSUE TITLE
Link to Firefox extension is dead (Wiki Implementations)

### ISSUE THREAD

**Issue by xypha** [chriszarate/supergenpass#96]
In Wiki's [Implementations](https://github.com/chriszarate/supergenpass/wiki/Implementations), the link to Firefox extension is dead.

> - [Firefox extension](https://addons.mozilla.org/firefox/addon/hash-password-generator/) by Tim Anderson

![Screenshot 2023-12-01 222550](https://github.com/chriszarate/supergenpass/assets/12472214/3f7a1ad6-f9d7-4d97-b5f3-ca2bfec2c891)

Screenshot of dead link -
![Screenshot 2023-12-01 222731](https://github.com/chriszarate/supergenpass/assets/12472214/d4090784-305d-4860-b8b9-0a6708886551)

There are some new implementations that you might check and add to the Wiki -
(I haven't checked these. Found them after a cursory search)

- [MySuperGenPass](https://addons.mozilla.org/en-GB/firefox/addon/mysupergenpass/) by [verylazyguy](https://addons.mozilla.org/en-GB/firefox/user/15042407/)
- [SuperGenPass Context Menu](https://addons.mozilla.org/en-GB/firefox/addon/supergenpass-context-menu/) by [Patrik Dudits](https://addons.mozilla.org/en-GB/firefox/user/14559444/)

**Comment by scottchiefbaker** [comment]
Your links are broken... they both link to the same page that is a 404.

**Comment by xypha** [comment]
> Your links are broken... they both link to the same page that is a 404.

don't know how that happened.. weird. \*shrug\* -- links should work now.. ah, the irony

**Comment by xypha** [comment]
closed with Wiki change https://github.com/chriszarate/supergenpass/wiki/Implementations/ae359aa5c19c9a2b605e5a342746bb4638623c63
